// Logger settings
log.enabled: true;
log.level: "debug";
log.toStdout: false;
log.file: "game.log";
log.timestampTags: false;
log.levelTags: true;

// VFS settings
vfs.appDataFolder: ".2048x2";

// Window settings (used in windowed mode)
window.display: 0;
window.width: 810;
window.height: 450;
window.x: "auto";
window.y: "auto";
window.resizable: false;
window.hiDPI: false;
window.title: "2048x2";
window.HDROutput: false;

// Display settings
fullscreen: false;
vsync: 1;
updatesPerSecond: 60;
hideConsole: true;

// Locale settings
//locale: "en_US";

// OpenGL settings
gl.debugOutput: true;
gl.outputColorProfile: "Gamma22";
gl.anisotropicFiltering: false;
gl.defaultTextureAnisotropy: 8;
gl.shaderCache.enabled: false;
