/*
Copyright (c) 2014-2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module board;

import std.math;
import std.random;
import std.conv;

import dlib.core.memory;
import dlib.core.ownership;
import dlib.core.compound;
import dlib.math.vector;
import dlib.image.color;

import dagon.graphics.drawable;
import dagon.graphics.font;
import dagon.ui.textline;

import pool;
import tile;
public import boardarray;

int digits(int n)
{
    int res = 0;
    do
    {
        n /= 10;
        res++;
    }
    while(n != 0);
    return res;
}

uint randomValue()
{
    return (cast(uint)dice(90, 10) + 1) * 2;
}

class Board: Owner
{
    Vector2f position = Vector2f(0, 0);
    float cellSize = 100;
    
    BoardArray array;
    
    Pool!(Tile, 16) tiles;
    
    uint state = 0;

    bool gameOver = false;
    bool win = false;
    int score = 0;

    uint movingTiles = 0;
    
    this(Owner owner)
    {
        super(owner);
    }
    
    Vector2f cellPosition(uint x, uint y)
    {
        return position + 
               Vector2f(0.5f, 0.5f) * cellSize + 
               Vector2f(x, y) * cellSize;
    }
    
    Vector2f vectorElemPosition(uint i, uint j, Direction dir)
    {
        if (dir == Direction.Left)
            return cellPosition(j, i);
        else if (dir == Direction.Right)
            return cellPosition(3 - j, i);
        else if (dir == Direction.Up)
            return cellPosition(i, j);
        else if (dir == Direction.Down)
            return cellPosition(i, 3 - j);
        else assert(0);
    }
    
    void turn(Direction dir)
    {
        if (state == 1)
            return;

        bool moved = false;

        movingTiles = 0;

        foreach(vi; 0..4)
        {
            auto vec = array.vector(vi, dir);
            auto arr = deref(vec);
            uint[4] dest;
            uint j = 0;
            
            foreach(uint i, v; arr)
            {
                if (arr[i] != 0)
                {
                    if (arr[i] == dest[j])
                    {
                        dest[j] += arr[i];
                        score += dest[j];

                        Vector2f pos = vectorElemPosition(vi, i, dir);
                        Vector2f target = vectorElemPosition(vi, j, dir);

                        auto tile = Tile(arr[i], pos, target);
                        tiles.add(tile);
                        movingTiles++;

                        j++;
                    }
                    else
                    {
                        if (dest[j] != 0) 
                            j++;
                        dest[j] = arr[i];

                        Vector2f pos = vectorElemPosition(vi, i, dir);
                        Vector2f target = vectorElemPosition(vi, j, dir);

                        auto tile = Tile(arr[i], pos, target);
                        tiles.add(tile);

                        movingTiles++;

                        if (j != i)
                        {
                            moved = true;
                        }
                    }
                }
            }
            
            *vec[0] = dest[0];
            *vec[1] = dest[1];
            *vec[2] = dest[2];
            *vec[3] = dest[3];
        }

        if (moved)
            createRandomCell();
        else
            if (availableCells.length == 0)
                gameOver = true;

        state = 1;
    }
    
    uint[4] deref(uint*[4] p)
    {
        uint[4] res;
        res[0] = *p[0];
        res[1] = *p[1];
        res[2] = *p[2];
        res[3] = *p[3];
        return res;
    }
    
    auto availableCells()
    {
        Pool!(Compound!(uint, uint), 16) res;
        foreach(uint x; 0..4)
        foreach(uint y; 0..4)
        {
            int val = array[x, y];
            if (val == 0)
                res.add(compound(x, y));
        }
        return res;
    }

    void createRandomCell(uint val)
    {
        auto cells = availableCells();

        Compound!(uint, uint) cell;
        if (cells.length)
        {
            cell = cells[uniform(0, cells.length)];
            array[cell[0], cell[1]] = val;
        }
        else
            gameOver = true;
    }

    void createRandomCell()
    {
        createRandomCell(randomValue);
    }
    
    void reset(uint v1, uint v2)
    {
        gameOver = false;
        win = false;
        score = 0;
        
        state = 0;
        tiles.clear();
        
        array.reset();
        
        createRandomCell(v1);
        createRandomCell(v2);
    }
}
