/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module main;

import std.stdio;
import std.conv;
import std.math;
import std.random;

import derelict.sdl.sdl;
import derelict.opengl.gl;

import dlib.math.vector;
import dlib.image.color;

import dgl.core.application;
import dgl.core.layer;
import dgl.core.drawable;
import dgl.ui.freeview;
import dgl.ui.ftfont;
import dgl.ui.textline;
import dgl.ui.i18n;

import board;
import boardarray;

class GameApp: Application
{
    alias eventManager this;

    Layer layer2d;
    Board board1;
    Board board2;
    
    bool gameEnd = false;

    this()
    {
        super(810, 450, "2048x2");

        clearColor = color3(0xbbada0);

        glDisable(GL_LIGHTING);
        glDisable(GL_DEPTH_TEST);
        glDisable(GL_CULL_FACE);

        layer2d = addLayer2D(0);
 
        string fontFilename = "./data/fonts/clearsans/ClearSans-Bold.ttf";
        auto font = new FreeTypeFont(fontFilename, 27);
        auto font2 = new FreeTypeFont(fontFilename, 16);

        board1 = new Board(font, font2);
        board1.position = Vector2f(0, 0);
        layer2d.addDrawable(board1);

        board2 = new Board(font, font2);
        board2.position = Vector2f(410, 0);
        layer2d.addDrawable(board2);

        resetBoards();
    }

    override void onQuit()
    {
        super.onQuit();
    }
    
    override void onKeyDown()
    {
        super.onKeyDown();
        
        if (!board1.gameOver || !board2.gameOver)
        {
            if (!board1.gameOver)
            {
                if (event_key == 'a')
                    board1.turn(Direction.Left);
                else if (event_key == 'd')
                    board1.turn(Direction.Right);
                else if (event_key == 'w')
                    board1.turn(Direction.Up);
                else if (event_key == 's')
                    board1.turn(Direction.Down);
            }
            if (!board2.gameOver)
            {
                if (event_key == SDLK_LEFT)
                    board2.turn(Direction.Left);
                else if (event_key == SDLK_RIGHT)
                    board2.turn(Direction.Right);
                else if (event_key == SDLK_UP)
                    board2.turn(Direction.Up);
                else if (event_key == SDLK_DOWN)
                    board2.turn(Direction.Down);
            }
        }
        else if (gameEnd)
        {        
            if (event_key == SDLK_RETURN)
                resetBoards();
        }
    }
    
    void setWinner()
    {
        board1.state = 2;
        board2.state = 2;
        
        if (board1.score > board2.score)
            board1.win = true;
        else if (board1.score < board2.score)
            board2.win = true;
        else
        {
            board1.win = true;
            board2.win = true;
        }
        
        gameEnd = true;
    }

    void resetBoards()
    {
        gameEnd = false;
        uint v1 = randomValue();
        uint v2 = randomValue();
        board1.reset(v1, v2);
        board2.reset(v1, v2);
    }
    
    override void onMouseButtonDown()
    {
        super.onMouseButtonDown();
    }
    
    override void onUpdate()
    {
        super.onUpdate();
        
        if (board1.gameOver && board2.gameOver)
            setWinner();
    }
}

void main()
{
    Locale.readLang("locale");
    auto app = new GameApp();
    app.run();
}

