/*
Copyright (c) 2014-2026 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/
module main;

import core.stdc.stdio;
import std.math;
import std.conv;
import std.algorithm;
import std.string;
import dagon;
import board;

Color4f[uint] colors = [
    0: color3(0xcdc0b4),
    2: color3(0xeee4da),
    4: color3(0xede0c8),
    8: color3(0xf2b179),
   16: color3(0xf59563),
   32: color3(0xf67c5f),
   64: color3(0xf65e3b),
  128: color3(0xedcf72),
  256: color3(0xedcc61),
  512: color3(0xedc850),
 1024: color3(0xedc53f),
 2048: color3(0xedc22e),
 4096: color3(0x5fdb93)
];

string[uint] stringPool = [
    0: "0",
    2: "2",
    4: "4",
    8: "8",
   16: "16",
   32: "32",
   64: "64",
  128: "128",
  256: "256",
  512: "512",
 1024: "1024",
 2048: "2048",
 4096: "4096"
];

struct BoardCell
{
    Entity bg;
    Entity text;
}

class BoardVisual: Owner
{
    PuzzleScene scene;
    Board board;
    
    BoardCell[16] staticCells;
    BoardCell[16] movingCells;
    
    float cellSize = 90.0f;
    
    this(PuzzleScene scene, Board board)
    {
        super(scene);
        this.scene = scene;
        this.board = board;
        
        auto mBg = scene.addMaterial();
        mBg.shader = scene.hudShader;
        mBg.baseColorFactor = color3(0xcdc0b4);
        mBg.depthWrite = false;
        mBg.useCulling = false;
        mBg.blendMode = Transparent;
        
        foreach(y; 0..4)
        foreach(x; 0..4)
        {
            Vector2f cellPos = board.cellPosition(x, y);
            
            auto bg = scene.addEntityHUD();
            bg.drawable = scene.quad;
            bg.material = mBg;
            bg.scaling = Vector3f(cellSize, cellSize, 1.0f);
            bg.position = Vector3f(cellPos.x - cellSize * 0.5f, cellPos.y - cellSize * 0.5f, 0.0f);
        }
        
        foreach(y; 0..4)
        foreach(x; 0..4)
        {
            Vector2f cellPos = board.cellPosition(x, y);
            
            auto bg = scene.addEntityHUD();
            bg.drawable = scene.quad;
            bg.scaling = Vector3f(cellSize, cellSize, 1.0f);
            bg.position = Vector3f(cellPos.x - cellSize * 0.5f, ceil(cellPos.y - cellSize * 0.5f), 0.0f);
            bg.visible = false;
            
            auto textLine = New!TextLine(scene.aFont1.font, "0", this);
            textLine.color = Color4f(0.0f, 0.0f, 0.0f, 1.0f);
            auto text = scene.addEntityHUD();
            text.drawable = textLine;
            text.position = Vector3f(cellPos.x - textLine.width * 0.5f, cellPos.y + textLine.height * 0.5f, 0.0f);
            text.visible = false;
            
            auto m = scene.addMaterial();
            m.shader = scene.hudShader;
            m.baseColorFactor = color3(0xcdc0b4);
            m.depthWrite = false;
            m.useCulling = false;
            m.blendMode = Transparent;
            bg.material = m;
            
            staticCells[y * 4 + x] = BoardCell(bg, text);
        }
        
        foreach(y; 0..4)
        foreach(x; 0..4)
        {
            Vector2f cellPos = board.cellPosition(x, y);
            
            auto bg = scene.addEntityHUD();
            bg.drawable = scene.quad;
            bg.scaling = Vector3f(cellSize, cellSize, 1.0f);
            bg.position = Vector3f(cellPos.x - cellSize * 0.5f, cellPos.y - cellSize * 0.5f, 0.0f);
            bg.visible = false;
            
            auto textLine = New!TextLine(scene.aFont1.font, "0", this);
            textLine.color = Color4f(0.0f, 0.0f, 0.0f, 1.0f);
            auto text = scene.addEntityHUD();
            text.drawable = textLine;
            text.position = Vector3f(cellPos.x - textLine.width * 0.5f, cellPos.y + textLine.height * 0.5f, 0.0f);
            text.visible = false;
            
            auto m = scene.addMaterial();
            m.shader = scene.hudShader;
            m.baseColorFactor = color3(0xcdc0b4);
            m.depthWrite = false;
            m.useCulling = false;
            m.blendMode = Transparent;
            bg.material = m;
            
            movingCells[y * 4 + x] = BoardCell(bg, text);
        }
    }
    
    void update(Time t)
    {
        // Update animation
        foreach(i; 0..board.tiles.length)
        {
            auto tile = &board.tiles.data[i];
            
            if (tile.active && tile.value > 0)
                tile.moveToPoint(tile.targetPosition, 2000.0f * t.delta);

            if (!tile.active && tile.unreg)
            {
                board.movingTiles--;
                tile.unreg = false;
            }
        }
        
        if (board.state == 1)
        {
            if (board.movingTiles == 0)
            {
                board.state = 0;
                board.tiles.clear();
            }
        }
        
        // Update visuals
        if (board.state == 0)
        {
            // Draw static board
            foreach(y; 0..4)
            foreach(x; 0..4)
            {
                auto cell = staticCells[y * 4 + x].bg;
                auto cellText = staticCells[y * 4 + x].text;
                auto cellTextLine = cast(TextLine)cellText.drawable;
                auto cellValue = board.array[x, y];
                
                if (cellValue > 0)
                {
                    cell.visible = true;
                    cellText.visible = true;
                    cell.material.baseColorFactor = colors[min(cellValue, 4096)];
                    Vector2f cellPos = board.cellPosition(x, y);
                    cell.position = Vector3f(cellPos.x - cellSize * 0.5f, cellPos.y - cellSize * 0.5f, 0.0f);
                    if (cellValue < 8)
                        cellTextLine.color = color3(0x776e65);
                    else
                        cellTextLine.color = color3(0xffffff);
                    
                    auto valPtr = cellValue in stringPool;
                    string s;
                    if (valPtr)
                        s = *valPtr;
                    else
                    {
                        s = cellValue.to!string;
                        stringPool[cellValue] = s;
                    }
                    
                    if (cellTextLine.text != s)
                        cellTextLine.setText(s);
                    
                    cellText.position = Vector3f(cellPos.x - cellTextLine.width * 0.5f, cellPos.y + cellTextLine.height * 0.5f, 0.0f);
                }
                else
                {
                    cellText.visible = false;
                    cell.visible = false;
                }
            }
            
            foreach(cell; movingCells)
            {
                cell.bg.visible = false;
                cell.text.visible = false;
            }
        }
        else if (board.state == 1)
        {
            // Draw animated tiles
            foreach(i; 0..board.tiles.length)
            {
                auto movingTile = movingCells[i].bg;
                auto cellText = movingCells[i].text;
                auto cellTextLine = cast(TextLine)cellText.drawable;
                auto tile = &board.tiles.data[i];
                
                if (tile.value > 0)
                {
                    movingTile.visible = true;
                    cellText.visible = true;
                    
                    Vector2f cellPos = tile.position;
                    movingTile.position = Vector3f(cellPos.x - cellSize * 0.5f, cellPos.y - cellSize * 0.5f, 0.0f);
                    movingTile.material.baseColorFactor = colors[min(tile.value, 4096)];
                    
                    if (tile.value < 8)
                        cellTextLine.color = color3(0x776e65);
                    else
                        cellTextLine.color = color3(0xffffff);
                    
                    auto valPtr = tile.value in stringPool;
                    string s;
                    if (valPtr)
                        s = *valPtr;
                    else
                    {
                        s = tile.value.to!string;
                        stringPool[tile.value] = s;
                    }
                    
                    if (cellTextLine.text != s)
                        cellTextLine.setText(s);
                    
                    cellText.position = Vector3f(cellPos.x - cellTextLine.width * 0.5f, cellPos.y + cellTextLine.height * 0.5f, 0.0f);
                }
                else
                {
                    cellText.visible = false;
                    movingTile.visible = false;
                }
            }
            
            foreach(cell; staticCells)
            {
                cell.bg.visible = false;
                cell.text.visible = false;
            }
        }
    }
}

class PuzzleScene: Scene
{
    GameApp app;
    
    ShapeQuad quad;
    HUDShader hudShader;
    
    FontAsset aFont1, aFont2;
    
    Board board1, board2;
    BoardVisual board1Visual, board2Visual;
    Entity fgLeft, fgRight;
    Material fgLeftMaterial, fgRightMaterial;
    
    TextLine scoreTextLineLeft, scoreTextLineRight;
    Entity scoreTextLeft, scoreTextRight;
    
    char[256] scoreLeftBuffer;
    char[256] scoreRightBuffer;
    
    TextLine gameOverTextLineLeft, gameOverTextLineRight;
    Entity gameOverTextLeft, gameOverTextRight;
    
    TextLine waitTextLineLeft, waitTextLineRight;
    Entity waitTextLeft, waitTextRight;
    
    TextLine winTextLine, loseTextLine;
    Entity finalTextLeft, finalTextRight;
    
    TextLine pressEnterTextLineWin, pressEnterTextLineLose;
    Entity pressEnterTextLeft, pressEnterTextRight;
    
    bool gameEnd = false;
    
    const(char)* scoreStr;
    
    this(GameApp app)
    {
        super(app);
        this.app = app;
    }

    override void beforeLoad()
    {
        aFont1 = New!FontAsset(27, app.pixelRatio, assetManager);
        assetManager.preloadExternalAsset(aFont1, "data/fonts/clearsans/ClearSans-Bold.ttf");
        
        aFont2 = New!FontAsset(16, app.pixelRatio, assetManager);
        assetManager.preloadExternalAsset(aFont2, "data/fonts/clearsans/ClearSans-Bold.ttf");
    }

    override void afterLoad()
    {
        environment.backgroundColor = color3(0xbbada0);

        board1 = New!Board(this);
        board1.position = Vector2f(0, 1);
        board1.reset(2, 2);
        
        board2 = New!Board(this);
        board2.position = Vector2f(409, 1);
        board2.reset(2, 2);
        
        quad = New!ShapeQuad(this);
        hudShader = New!HUDShader(assetManager);
        
        board1Visual = New!BoardVisual(this, board1);
        board2Visual = New!BoardVisual(this, board2);
        
        fgLeftMaterial = addMaterial();
        fgLeftMaterial.shader = hudShader;
        fgLeftMaterial.baseColorFactor = Color4f(0.0f, 0.0f, 0.0f, 0.75f);
        fgLeftMaterial.depthWrite = false;
        fgLeftMaterial.useCulling = false;
        fgLeftMaterial.blendMode = Transparent;
        
        fgRightMaterial = addMaterial();
        fgRightMaterial.shader = hudShader;
        fgRightMaterial.baseColorFactor = Color4f(0.0f, 0.0f, 0.0f, 0.75f);
        fgRightMaterial.depthWrite = false;
        fgRightMaterial.useCulling = false;
        fgRightMaterial.blendMode = Transparent;
        
        fgLeft = addEntityHUD();
        fgLeft.drawable = quad;
        fgLeft.scaling = Vector3f(app.drawableWidth * 0.5f, app.drawableHeight, 1.0f);
        fgLeft.position = Vector3f(0.0f, 0.0f, 0.0f);
        fgLeft.visible = false;
        fgLeft.material = fgLeftMaterial;
        
        fgRight = addEntityHUD();
        fgRight.drawable = quad;
        fgRight.scaling = Vector3f(app.drawableWidth * 0.5f, app.drawableHeight, 1.0f);
        fgRight.position = Vector3f(app.drawableWidth * 0.5f, 0.0f, 0.0f);
        fgRight.visible = false;
        fgRight.material = fgRightMaterial;
        
        scoreTextLineLeft = New!TextLine(aFont1.font, "Score: 0", this);
        scoreTextLineLeft.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        scoreTextLeft = addEntityHUD();
        scoreTextLeft.drawable = scoreTextLineLeft;
        scoreTextLeft.position = Vector3f(app.drawableWidth * 0.25f - scoreTextLineLeft.width * 0.5f, app.drawableHeight - 15.0f, 0.0f);
        scoreTextLeft.visible = true;
        
        scoreTextLineRight = New!TextLine(aFont1.font, "Score: 0", this);
        scoreTextLineRight.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        scoreTextRight = addEntityHUD();
        scoreTextRight.drawable = scoreTextLineRight;
        scoreTextRight.position = Vector3f(app.drawableWidth * 0.75f - scoreTextLineRight.width * 0.5f, app.drawableHeight - 15.0f, 0.0f);
        scoreTextRight.visible = true;
        
        gameOverTextLineLeft = New!TextLine(aFont1.font, app.translation.get("GameOver"), this);
        gameOverTextLineLeft.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        gameOverTextLeft = addEntityHUD();
        gameOverTextLeft.drawable = gameOverTextLineLeft;
        gameOverTextLeft.position = Vector3f(app.drawableWidth * 0.25f - gameOverTextLineLeft.width * 0.5f, 190.0f, 0.0f);
        gameOverTextLeft.visible = false;
        
        gameOverTextLineRight = New!TextLine(aFont1.font, app.translation.get("GameOver"), this);
        gameOverTextLineRight.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        gameOverTextRight = addEntityHUD();
        gameOverTextRight.drawable = gameOverTextLineRight;
        gameOverTextRight.position = Vector3f(app.drawableWidth * 0.75f - gameOverTextLineRight.width * 0.5f, 190.0f, 0.0f);
        gameOverTextRight.visible = false;
        
        waitTextLineLeft = New!TextLine(aFont2.font, app.translation.get("WaitForPlayer2"), this);
        waitTextLineLeft.color = color3(0xf2b179);
        waitTextLeft = addEntityHUD();
        waitTextLeft.drawable = waitTextLineLeft;
        waitTextLeft.position = Vector3f(app.drawableWidth * 0.25f - waitTextLineLeft.width * 0.5f, 225.0f, 0.0f);
        waitTextLeft.visible = false;
        
        waitTextLineRight = New!TextLine(aFont2.font, app.translation.get("WaitForPlayer1"), this);
        waitTextLineRight.color = color3(0xf2b179);
        waitTextRight = addEntityHUD();
        waitTextRight.drawable = waitTextLineRight;
        waitTextRight.position = Vector3f(app.drawableWidth * 0.75f - waitTextLineRight.width * 0.5f, 225.0f, 0.0f);
        waitTextRight.visible = false;
        
        winTextLine = New!TextLine(aFont1.font, app.translation.get("YouWin"), this);
        winTextLine.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        
        loseTextLine = New!TextLine(aFont1.font, app.translation.get("YouLose"), this);
        loseTextLine.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        
        pressEnterTextLineWin = New!TextLine(aFont2.font, app.translation.get("PressEnter"), this);
        pressEnterTextLineWin.color = Color4f(1.0f, 1.0f, 1.0f, 1.0f);
        
        pressEnterTextLineLose = New!TextLine(aFont2.font, app.translation.get("PressEnter"), this);
        pressEnterTextLineLose.color = color3(0xf2b179);
        
        finalTextLeft = addEntityHUD();
        finalTextLeft.drawable = winTextLine;
        finalTextLeft.position = Vector3f(app.drawableWidth * 0.25f - winTextLine.width * 0.5f, 190.0f, 0.0f);
        finalTextLeft.visible = false;
        
        finalTextRight = addEntityHUD();
        finalTextRight.drawable = winTextLine;
        finalTextRight.position = Vector3f(app.drawableWidth * 0.75f - winTextLine.width * 0.5f, 190.0f, 0.0f);
        finalTextRight.visible = false;
        
        pressEnterTextLeft = addEntityHUD();
        pressEnterTextLeft.drawable = pressEnterTextLineLose;
        pressEnterTextLeft.position = Vector3f(app.drawableWidth * 0.25f - pressEnterTextLineLose.width * 0.5f, 225.0f, 0.0f);
        pressEnterTextLeft.visible = false;
        
        pressEnterTextRight = addEntityHUD();
        pressEnterTextRight.drawable = pressEnterTextLineLose;
        pressEnterTextRight.position = Vector3f(app.drawableWidth * 0.75f - pressEnterTextLineLose.width * 0.5f, 225.0f, 0.0f);
        pressEnterTextRight.visible = false;
        
        scoreStr = app.translation.get("Score").toStringz;
    }
    
    override void onUpdate(Time t)
    {
        board1Visual.update(t);
        board2Visual.update(t);
        
        if (!gameEnd)
        {
            if (board1.gameOver && board2.gameOver)
            {
                finishGame();
                gameEnd = true;
            }
            else
            {
                if (board1.gameOver)
                    showLeftGameOverScreen();
                else
                {
                    size_t numChars = min(scoreLeftBuffer.length, snprintf(scoreLeftBuffer.ptr, scoreLeftBuffer.length, scoreStr, board1.score));
                    scoreTextLineLeft.setText(cast(string)scoreLeftBuffer[0..numChars]);
                    scoreTextLeft.position.x = app.drawableWidth * 0.25f - scoreTextLineLeft.width * 0.5f;
                }
                
                if (board2.gameOver)
                    showRightGameOverScreen();
                else
                {
                    size_t numChars = min(scoreRightBuffer.length, snprintf(scoreRightBuffer.ptr, scoreRightBuffer.length, scoreStr, board2.score));
                    scoreTextLineRight.setText(cast(string)scoreRightBuffer[0..numChars]);
                    scoreTextRight.position.x = app.drawableWidth * 0.75f - scoreTextLineRight.width * 0.5f;
                }
            }
        }
    }
    
    void finishGame()
    {
        if (board1.score > board2.score)
        {
            board1.win = true;
            showLeftFinalScreen(true);
            showRightFinalScreen(false);
        }
        else if (board1.score < board2.score)
        {
            board2.win = true;
            showLeftFinalScreen(false);
            showRightFinalScreen(true);
        }
        else
        {
            board1.win = true;
            board2.win = true;
            showLeftFinalScreen(true);
            showRightFinalScreen(true);
        }
    }
    
    void showLeftFinalScreen(bool win)
    {
        board1.state = 2;
        
        gameOverTextLeft.visible = false;
        waitTextLeft.visible = false;
        
        if (win)
        {
            fgLeftMaterial.baseColorFactor = color3(0xefad3f);
            fgLeftMaterial.baseColorFactor.a = 0.75f;
            
            finalTextLeft.drawable = winTextLine;
            finalTextLeft.position.x = app.drawableWidth * 0.25f - winTextLine.width * 0.5f;
            
            pressEnterTextLeft.drawable = pressEnterTextLineWin;
        }
        else
        {
            fgLeftMaterial.baseColorFactor = Color4f(0.0f, 0.0f, 0.0f, 0.75f);
            
            finalTextLeft.drawable = loseTextLine;
            finalTextLeft.position.x = app.drawableWidth * 0.25f - loseTextLine.width * 0.5f;
            
            pressEnterTextLeft.drawable = pressEnterTextLineLose;
        }
        
        fgLeft.visible = true;
        finalTextLeft.visible = true;
        pressEnterTextLeft.visible = true;
    }
    
    void showRightFinalScreen(bool win)
    {
        board2.state = 2;
        
        gameOverTextRight.visible = false;
        waitTextRight.visible = false;
        
        if (win)
        {
            fgRightMaterial.baseColorFactor = color3(0xefad3f);
            fgRightMaterial.baseColorFactor.a = 0.75f;
            
            finalTextRight.drawable = winTextLine;
            finalTextRight.position.x = app.drawableWidth * 0.75f - winTextLine.width * 0.5f;
            
            pressEnterTextRight.drawable = pressEnterTextLineWin;
        }
        else
        {
            fgRightMaterial.baseColorFactor = Color4f(0.0f, 0.0f, 0.0f, 0.75f);
            
            finalTextRight.drawable = loseTextLine;
            finalTextRight.position.x = app.drawableWidth * 0.75f - loseTextLine.width * 0.5f;
            
            pressEnterTextRight.drawable = pressEnterTextLineLose;
        }
        
        fgRight.visible = true;
        finalTextRight.visible = true;
        pressEnterTextRight.visible = true;
    }
    
    void showLeftGameOverScreen()
    {
        fgLeftMaterial.baseColorFactor = Color4f(0.0f, 0.0f, 0.0f, 0.75f);
        fgLeft.visible = true;
        gameOverTextLeft.visible = true;
        waitTextLeft.visible = true;
    }
    
    void showRightGameOverScreen()
    {
        fgRightMaterial.baseColorFactor = Color4f(0.0f, 0.0f, 0.0f, 0.75f);
        fgRight.visible = true;
        gameOverTextRight.visible = true;
        waitTextRight.visible = true;
    }
    
    override void onKeyDown(int key)
    {
        if (gameEnd)
        {
            if (key == KEY_RETURN)
            {
                resetBoards();
            }
        }
        else
        {
            if (!board1.gameOver)
            {
                if (key == KEY_A)
                    board1.turn(Direction.Left);
                else if (key == KEY_D)
                    board1.turn(Direction.Right);
                else if (key == KEY_W)
                    board1.turn(Direction.Up);
                else if (key == KEY_S)
                    board1.turn(Direction.Down);
            }
            
            if (!board2.gameOver)
            {
                if (key == KEY_LEFT)
                    board2.turn(Direction.Left);
                else if (key == KEY_RIGHT)
                    board2.turn(Direction.Right);
                else if (key == KEY_UP)
                    board2.turn(Direction.Up);
                else if (key == KEY_DOWN)
                    board2.turn(Direction.Down);
            }
        }
    }
    
    void resetBoards()
    {
        fgLeft.visible = false;
        fgRight.visible = false;
        gameOverTextLeft.visible = false;
        waitTextLeft.visible = false;
        gameOverTextRight.visible = false;
        waitTextRight.visible = false;
        finalTextLeft.visible = false;
        finalTextRight.visible = false;
        pressEnterTextLeft.visible = false;
        pressEnterTextRight.visible = false;
        board1.reset(2, 2);
        board2.reset(2, 2);
        gameEnd = false;
    }
}

class GameApp: Game2D
{
    this(uint w, uint h, bool fullscreen, string title, string[] args)
    {
        super(w, h, fullscreen, title, args);
        currentScene = New!PuzzleScene(this);
    }
}

void main(string[] args)
{
    GameApp app = New!GameApp(810, 450, false, "2048x2", args);
    app.run();
    Delete(app);
}
