/*
Copyright (c) 2014 Timur Gafarov 

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

module tile;

import std.math;
import derelict.opengl.gl;
import dlib.math.vector;

struct Tile
{
    uint value = 0;
    Vector2f position = Vector2f(0, 0);
    Vector2f targetPosition = Vector2f(0, 0);
    bool active = false;
    bool unreg = true;

    this(Vector2f srcPos)
    {
        this.position = srcPos;
    }

    this(uint value, Vector2f srcPos)
    {
        this.value = value;
        this.position = srcPos;
    }

    this(uint value, Vector2f srcPos, Vector2f targetPos)
    {
        this.value = value;
        this.position = srcPos;
        this.targetPosition = targetPos;
        this.active = true;
    }

    void moveToPoint(Vector2f pt, float speed)
    {
        Vector2f dir = pt - position;
        float dist = dir.length;
        dir.normalize();

        if (abs(dist) > 0.001f)
        {
            if (dist >= speed)
                position += dir * speed;
            else
                position += dir * dist;
        }
        else
        {
            position = pt;
            active = false;
        }
    }

    void draw(double dt)
    {
        if (active && value > 0)
            moveToPoint(targetPosition, 3300.0f * dt);

        glPushMatrix();
        glTranslatef(position.x, position.y, 0);
        glScalef(90, 90, 90);
        glBegin(GL_QUADS);
        glVertex2f(-0.5f, -0.5f);
        glVertex2f(0.5f, -0.5f);
        glVertex2f(0.5f, 0.5f);
        glVertex2f(-0.5f, 0.5f);
        glEnd();
        glPopMatrix();
    }
}

